name: Reusable whitespace WF

on:
  workflow_call:
    inputs:
      tpm2tools_branch:
        required: false
        type: string
      tpm2tss_branch:
        required: false
        type: string

jobs:
  whitespace-check:
    name: Whitespace check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Perform Whitespace Check
        env:
          BASE_REF: master
          TPM2TOOLS_BRANCH: ${{ inputs.tpm2tools_branch }}
          TPM2TSS_BRANCH: ${{ inputs.tpm2tss_branch }}
        run: |
          echo Tools branch is: $TPM2TOOLS_BRANCH
          echo Tools branch is: $TPM2TSS_BRANCH
          ls
          pwd
          echo ${{ github.action_path }}
          git fetch origin "$BASE_REF" && git diff --check "origin/$BASE_REF"
